
[window]
padding = {x = 10, y = 10}

[font]
size = 18.0

[font.bold]
family = "CartographCF"
style = "Bold"

[font.bold_italic]
family = "CartographCF"
style = "Bold Italic"

[font.italic]
family = "CartographCF"
style = "Italic"

[font.normal]
family = "CartographCF"
style = "Regular"
