#+Title: GNU Emacs Configuration

* Early init

Since we are using =straight.el= we want to make sure that
=package.el= does not do anything unexpected, such as loading packages
that are already being loaded by =straight.el=.

#+begin_src emacs-lisp :tangle "early-init.el"
  (setq package-enable-at-startup nil)  
#+end_src

* Bootstrap straight.el

To be able to use =straight.el= we need to bootstrap it at the
beginning of our init file.

#+begin_src emacs-lisp :tangle "init.el"
  ;;; Bootstrap straight.el

  (defvar bootstrap-version)
  (let ((bootstrap-file
         (expand-file-name
          "straight/repos/straight.el/bootstrap.el"
          (or (bound-and-true-p straight-base-dir)
              user-emacs-directory)))
        (bootstrap-version 7))
    (unless (file-exists-p bootstrap-file)
      (with-current-buffer
          (url-retrieve-synchronously
           "https://raw.githubusercontent.com/radian-software/straight.el/develop/install.el"
           'silent 'inhibit-cookies)
        (goto-char (point-max))
        (eval-print-last-sexp)))
    (load bootstrap-file nil 'nomessage))
#+end_src

We want to use the =use-package= macro, which is enabled by our first
line. Since the vast majority of packages will use ~:straight t~ we
set this to be the default and use ~:straight nil~ for the exceptions.

#+begin_src emacs-lisp :tangle "init.el"
  (straight-use-package 'use-package)
  (setopt straight-use-package-by-default t)
#+end_src

* Global options

Setting options that do not relate to specific packages or features.

#+begin_src emacs-lisp :tangle "init.el"
  ;;; Options

  (setopt menu-bar-mode nil
  	tool-bar-mode nil
  	scroll-bar-mode nil
  	display-line-numbers t
  	electric-pair-mode t)
#+end_src

Some custom keybinds.

#+begin_src emacs-lisp :tangle "init.el"
  (keymap-global-set "M-n" 'scroll-up-line)
  (keymap-global-set "M-p" 'scroll-down-line)

  (defun my/kill-whole-line-backwards (&optional arg)
    "Kill current line and preceding newline.
With prefix ARG, kill that many lines starting from the current line backwards.
If ARG is negative, kill forwards. Also kill the trailing newline.
If ARG is zero, kill current line."
    (interactive "p")
    (kill-whole-line (- arg)))
  (keymap-global-set "C-S-k" 'my/kill-whole-line-backwards)

#+end_src

This option puts all tilde files into a single directory instead of
cluttering the working directory.

#+begin_src emacs-lisp :tangle "init.el"
  (setopt backup-directory-alist '(("." . "~/.emacs.d/backup")))
#+end_src

* Theme
** Load theme.

#+begin_src emacs-lisp :tangle "init.el"
  ;;; Theme and font

  (setopt modus-themes-mixed-fonts t)
  (load-theme 'modus-operandi)
#+end_src

** Set preffered fonts.

#+begin_src emacs-lisp :tangle "init.el"
  (set-face-attribute 'default nil
    		    :family "Aporetic Serif Mono"
    		    :height 140)

  (set-face-attribute 'fixed-pitch nil
    		    :family "Aporetic Sans Mono")

  (set-face-attribute 'variable-pitch nil
    		    :family "Aporetic Serif")
#+end_src

** Variable pitch mode

Source: [[https://protesilaos.com/emacs/dotemacs#h:60d6aae2-6e4b-402c-b6a8-411fc49a6857][Protesilaus Stavrou]]

#+begin_src emacs-lisp :tangle "init.el"
  (defun my/enable-variable-pitch-mode ()
    (unless (derived-mode-p 'mhtml-mode 'nxml-mode 'yaml-mode)
      (variable-pitch-mode t)))

  (add-hook 'text-mode-hook #'my/enable-variable-pitch-mode)
#+end_src

* Org

#+begin_src emacs-lisp :tangle "init.el"
  ;;; Org mode

  (setopt org-startup-indented t)
  (setopt org-hide-emphasis-markers t)
#+end_src

* Packages
** Magit

GUI for git.

#+begin_src emacs-lisp :tangle "init.el"
  ;;; Magit

  (use-package magit)
#+end_src

** Exec path from shell

This will make sure that ~exec-path~ is the value from the users shell
=PATH=, instead of the =PATH= from where Emacs was launched. Personally, I
find this much less confusing; I cannot recall another time where I
have interacted with a =PATH= that was not the one in my shell. The
reason why this is important to configure is because some packages
need to communicate with programs outside of Emacs, most notably ~eglot~
needs to know about LSP-servers on the machine.

#+begin_src emacs-lisp :tangle "init.el"
  ;;; Exec path from shell

  (use-package exec-path-from-shell
    :init
    (when (memq window-system '(pgtk))
      (exec-path-from-shell-initialize)))
#+end_src

** Expand region

Efficiently select text around the point.

#+begin_src emacs-lisp :tangle "init.el"
  (use-package expand-region
    :bind
    ("C-+" . er/expand-region))
#+end_src

** Multiple cursor

#+begin_src emacs-lisp :tangle "init.el"
  (use-package multiple-cursors
    :bind
    (("C->" . mc/mark-next-like-this)
     ("C-<" . mc/mark-previous-like-this)))
#+end_src

** Minibuffer
*** Vertico

Instead of displaying minibuffer completions inside a seperate buffer
vertico will show them directly. It also provides a live preview, so
it is not necessary to hit tab repeatedly when typing commands.

#+begin_src emacs-lisp :tangle "init.el"
  (use-package vertico
    :init
    (vertico-mode))
#+end_src

*** Marginalia

Provide short description of interactive commands in the minibuffer.

#+begin_src emacs-lisp :tangle "init.el"
  (use-package marginalia
    :init
    (marginalia-mode))
#+end_src

*** Orderless

A more forgiving completion method. Uses spaces instead of * and shows
result also with search words reordered.

#+begin_src emacs-lisp :tangle "init.el"
  (use-package orderless
    :custom
    (completion-styles '(orderless basic))
    (completion-category-overrides '((file (styles partial-completion)))))
#+end_src

*** Consult

Gather different =Switch to= commands into a single prompt. Also display
preview of selection live.

#+begin_src emacs-lisp :tangle "init.el"
  (use-package consult
    :bind
    (("C-c b" . consult-buffer)
     ("C-c g" . consult-grep)
     ("C-c f" . consult-find)))
#+end_src

*** Recentf

Track visited files.

#+begin_src emacs-lisp :tangle "init.el"
  (recentf-mode t)
#+end_src

*** Embark

#+begin_src emacs-lisp :tangle "init.el"
  (use-package embark
    :bind
    (("C-$" . embark-act)))
  (use-package embark-consult)
#+end_src

** IDE
*** Treesitter

#+begin_src emacs-lisp :tangle "init.el"
  (use-package treesit-auto
    :custom
    (treesit-auto-install 'prompt)
    :config
    (treesit-auto-add-to-auto-mode-alist 'all)
    (global-treesit-auto-mode))
#+end_src

*** Eglot

#+begin_src emacs-lisp :tangle "init.el"
  (defun my/enable-eglot ()
    (when (derived-mode-p 'c++-ts-mode 'c-ts-mode 'tsx-ts-mode 'typescript-ts-mode 'js-ts-mode)
      (eglot-ensure)))

  (defun my/prevent-eglot-completion ()
    (remove-hook 'completion-at-point-functions #'eglot-completion-at-point t))
  
  (add-hook 'prog-mode-hook 'my/enable-eglot)
  (add-hook 'eglot-managed-mode-hook 'my/prevent-eglot-completion)
#+end_src

*** Markdown mode

This is needed by Eldoc to correctly display information from certain LSPs.

#+begin_src emacs-lisp :tangle "init.el"
  (use-package markdown-mode)
#+end_src

*** Corfu

Display completions at point inside buffer.

#+begin_src emacs-lisp :tangle "init.el"
  (use-package corfu
    :init
    (global-corfu-mode))
#+end_src

*** Cape

#+begin_src emacs-lisp :tangle "init.el"
  (use-package cape
    :init
    (add-hook 'completion-at-point-functions #'cape-dabbrev))
#+end_src

*** Prettier

Opinionated code formatting for web development.

#+begin_src emacs-lisp :tangle "init.el"
  (use-package prettier-js
    :hook ((js-ts-mode typescript-ts-mode tsx-ts-mode html-ts-mode css-ts-mode) .
  	 prettier-js-mode))

  (defun my/format-on-save ()
    (add-hook 'before-save-hook 'prettier-js-prettify nil 'make-it-local))
    
  (add-hook 'js-ts-mode 'my/format-on-save)  
  (add-hook 'typescript-ts-mode 'my/format-on-save)  
  (add-hook 'tsx-ts-mode 'my/format-on-save)  
  (add-hook 'html-ts-mode 'my/format-on-save)  
  (add-hook 'css-ts-mode 'my/format-on-save)

  (setopt js-indent-level 2) ; same as prettier
  (setopt css-indent-offset 2)
#+end_src

